networks: {}
version: '2.0'

services:
  nginx:
    image: nginx:1.11.8
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "26578:26578"
    links:
      - "puma:puma"
    restart: always

  puma:
    build:
      context: ./
      dockerfile: ./docker/puma/Dockerfile
    environment:
      - THREAD_MIN=8
      - THREAD_MAX=32
      - WORKER_COUNT=3
    volumes:
      - ./app:/app
    command: "foreman start"
    links:
      - "fluentd:fluentd"
    restart: always

  fluentd:
    build:
      context: ./
      dockerfile: ./docker/fluentd/Dockerfile
    volumes:
      - ./docker/fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
      - ./data/fluentd:/data
    env_file: ./.env/app.env
    restart: always

  norikra:
    image: minimum2scp/norikra
    volumes:
      - ./docker/norikra/querys:/norikra/querys
