FROM nginx:1.11.8

RUN \
  apt-get update && \
  apt-get install -y wget unzip && \
  mkdir /etc/nginx/ssl && \
  cd /etc/nginx/ssl && \
  openssl genrsa 2048 > server.key && \
  openssl req -batch -new -newkey rsa:2048 -nodes -sha256 -days 365 -key server.key -out server.csr && \
  openssl x509 -in server.csr -out server.crt -req -signkey server.key -days 365 && \
  openssl x509 -days 3650 -req -signkey server.key < server.csr > server.crt && \
  chown nginx:nginx server.*
